apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: default
  labels:
    app: hello-world
    homework: "1.2"
    task: "pod-creation"
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
