apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
  namespace: default
  labels:
    app: data-exchange
    homework: "2.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange
  template:
    metadata:
      labels:
        app: data-exchange
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: busybox-writer
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              echo "Data from busybox at $(date)" >> /data/shared-file.txt
              sleep 5
            done
        volumeMounts:
        - name: shared-data
          mountPath: /data
      - name: multitool-reader
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        ports:
        - containerPort: 1180
        command: ["/bin/sh", "-c"]
        args:
          - |
            tail -f /data/shared-file.txt
        volumeMounts:
        - name: shared-data
          mountPath: /data
