apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv-for-sc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-local
  hostPath:
    path: /mnt/data/k8s-pv-sc
    type: DirectoryOrCreate
